//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    public partial class CourseView
    {
        public string StudyProgramName { get; set; }
        public int CourseId { get; set; }
        public int StudyProgramId { get; set; }
        public int ProfessorId { get; set; }
        public string Name { get; set; }
        public string Assistant { get; set; }
        public int? ETCS { get; set; }
        public string ProfessorName { get; set; }
    }
}
