//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    public partial class ExamRegistrationView
    {
        public int ExamRegistrationId { get; set; }
        public int StudentId { get; set; }
        public int ExamId { get; set; }
        public bool IsRegistred { get; set; }
        public string NameAndSurname { get; set; }
    }
}
