//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    
    public partial class ExamView
    {
        public int ExamId { get; set; }
        public int ExamPeriodId { get; set; }
        public int CourseId { get; set; }
        public DateTime DateAndTime { get; set; }
        public string Place { get; set; }
        public bool? IsPassed { get; set; }
        public int? Price { get; set; }
        public string ExamPeriodName { get; set; }
        public string CourseName { get; set; }
    }
}
