//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    public partial class ExamResultView
    {
        public string NameAndSurname { get; set; }
        public int ExamResultsId { get; set; }
        public int ExamRegistrationId { get; set; }
        public int? TermPaper { get; set; }
        public int? FirstTest { get; set; }
        public int? SecondTest { get; set; }
        public int? WritenExam { get; set; }
        public int? Total { get; set; }
        public int? Evaluation { get; set; }
    }
}
