//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentDbEntities : DbContext
    {
        public StudentDbEntities()
            : base("name=StudentDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tblCalendars> tblCalendars { get; set; }
        public DbSet<tblCourses> tblCourses { get; set; }
        public DbSet<tblDepartments> tblDepartments { get; set; }
        public DbSet<tblExamPeriods> tblExamPeriods { get; set; }
        public DbSet<tblExamRegistrations> tblExamRegistrations { get; set; }
        public DbSet<tblExamResults> tblExamResults { get; set; }
        public DbSet<tblExams> tblExams { get; set; }
        public DbSet<tblProfessors> tblProfessors { get; set; }
        public DbSet<tblStudents> tblStudents { get; set; }
        public DbSet<tblStudyPrograms> tblStudyPrograms { get; set; }
        public DbSet<tblTasks> tblTasks { get; set; }
        public DbSet<CourseView> CourseView { get; set; }
        public DbSet<StudentView> StudentView { get; set; }
        public DbSet<StudyProgramView> StudyProgramView { get; set; }
        public DbSet<ExamView> ExamView { get; set; }
        public DbSet<ExamRegistrationView> ExamRegistrationView { get; set; }
        public DbSet<ExamResultView> ExamResultView { get; set; }
    }
}
