//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    
    public partial class StudentView
    {
        public string StudyProgramName { get; set; }
        public string DepartmantName { get; set; }
        public int DepartmentId { get; set; }
        public int StudentId { get; set; }
        public int StudyProgramId { get; set; }
        public string NameAndSurname { get; set; }
        public string BirthPlace { get; set; }
        public DateTime? BirthDate { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public int? StudyYear { get; set; }
        public int? Balance { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
