//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    public partial class StudyProgramView
    {
        public string DepartmentName { get; set; }
        public int DepartmentId { get; set; }
        public int StudyProgramId { get; set; }
        public int SPdepartmentId { get; set; }
        public string Name { get; set; }
        public int? BudgetPlaces { get; set; }
        public int? SelffinancedPlaces { get; set; }
        public int? Tuition { get; set; }
    }
}
