//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourses
    {
        public tblCourses()
        {
            this.tblExams = new HashSet<tblExams>();
            this.tblTasks = new HashSet<tblTasks>();
        }
    
        public int CourseId { get; set; }
        public int StudyProgramId { get; set; }
        public int ProfessorId { get; set; }
        public string Name { get; set; }
        public string Assistant { get; set; }
        public Nullable<int> ETCS { get; set; }
    
        public virtual tblProfessors tblProfessors { get; set; }
        public virtual tblStudyPrograms tblStudyPrograms { get; set; }
        public virtual ICollection<tblExams> tblExams { get; set; }
        public virtual ICollection<tblTasks> tblTasks { get; set; }
    }
}
