//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCalendars
    {
        public int CalendarId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> ExamRegistrationId { get; set; }
    
        public virtual tblExamRegistrations tblExamRegistrations { get; set; }
        public virtual tblTasks tblTasks { get; set; }
    }
}
