//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartments
    {
        public tblDepartments()
        {
            this.tblStudyPrograms = new HashSet<tblStudyPrograms>();
        }
    
        public int DepartmentId { get; set; }
        public string Name { get; set; }
        public Nullable<int> FoundationYear { get; set; }
        public string DepartmentHead { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<tblStudyPrograms> tblStudyPrograms { get; set; }
    }
}
