//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExamResults
    {
        public int ExamResultsId { get; set; }
        public int ExamRegistrationId { get; set; }
        public Nullable<int> TermPaper { get; set; }
        public Nullable<int> FirstTest { get; set; }
        public Nullable<int> SecondTest { get; set; }
        public Nullable<int> WritenExam { get; set; }
        public Nullable<int> Evaluation { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual tblExamRegistrations tblExamRegistrations { get; set; }
    }
}
