//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExamRegistrations
    {
        public tblExamRegistrations()
        {
            this.tblCalendars = new HashSet<tblCalendars>();
            this.tblExamResults = new HashSet<tblExamResults>();
        }
    
        public int ExamRegistrationId { get; set; }
        public int StudentId { get; set; }
        public int ExamId { get; set; }
        public bool IsRegistred { get; set; }
    
        public virtual ICollection<tblCalendars> tblCalendars { get; set; }
        public virtual ICollection<tblExamResults> tblExamResults { get; set; }
        public virtual tblExams tblExams { get; set; }
        public virtual tblStudents tblStudents { get; set; }
    }
}
