//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudents
    {
        public tblStudents()
        {
            this.tblExamRegistrations = new HashSet<tblExamRegistrations>();
            this.tblTasks = new HashSet<tblTasks>();
        }
    
        public int StudentId { get; set; }
        public int StudyProgramId { get; set; }
        public string NameAndSurname { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> StudyYear { get; set; }
        public Nullable<int> Balance { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<tblExamRegistrations> tblExamRegistrations { get; set; }
        public virtual tblStudyPrograms tblStudyPrograms { get; set; }
        public virtual ICollection<tblTasks> tblTasks { get; set; }
    }
}
