//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudyPrograms
    {
        public tblStudyPrograms()
        {
            this.tblCourses = new HashSet<tblCourses>();
            this.tblStudents = new HashSet<tblStudents>();
        }
    
        public int StudyProgramId { get; set; }
        public int DepartmentId { get; set; }
        public string Name { get; set; }
        public Nullable<int> BudgetPlaces { get; set; }
        public Nullable<int> SelffinancedPlaces { get; set; }
        public Nullable<int> Tuition { get; set; }
    
        public virtual ICollection<tblCourses> tblCourses { get; set; }
        public virtual tblDepartments tblDepartments { get; set; }
        public virtual ICollection<tblStudents> tblStudents { get; set; }
    }
}
