//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFStudy.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/Repository.Model")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameAndSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudyProgramIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyProgramNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StudyYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthPlace {
            get {
                return this.BirthPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthPlaceField, value) != true)) {
                    this.BirthPlaceField = value;
                    this.RaisePropertyChanged("BirthPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameAndSurname {
            get {
                return this.NameAndSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameAndSurnameField, value) != true)) {
                    this.NameAndSurnameField = value;
                    this.RaisePropertyChanged("NameAndSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudyProgramId {
            get {
                return this.StudyProgramIdField;
            }
            set {
                if ((this.StudyProgramIdField.Equals(value) != true)) {
                    this.StudyProgramIdField = value;
                    this.RaisePropertyChanged("StudyProgramId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudyProgramName {
            get {
                return this.StudyProgramNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyProgramNameField, value) != true)) {
                    this.StudyProgramNameField = value;
                    this.RaisePropertyChanged("StudyProgramName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StudyYear {
            get {
                return this.StudyYearField;
            }
            set {
                if ((this.StudyYearField.Equals(value) != true)) {
                    this.StudyYearField = value;
                    this.RaisePropertyChanged("StudyYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudyProgram", Namespace="http://schemas.datacontract.org/2004/07/Repository.Model")]
    [System.SerializableAttribute()]
    public partial class StudyProgram : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BudgetPlacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SelffinancedPlacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudyProgramIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TuitionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BudgetPlaces {
            get {
                return this.BudgetPlacesField;
            }
            set {
                if ((this.BudgetPlacesField.Equals(value) != true)) {
                    this.BudgetPlacesField = value;
                    this.RaisePropertyChanged("BudgetPlaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SelffinancedPlaces {
            get {
                return this.SelffinancedPlacesField;
            }
            set {
                if ((this.SelffinancedPlacesField.Equals(value) != true)) {
                    this.SelffinancedPlacesField = value;
                    this.RaisePropertyChanged("SelffinancedPlaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudyProgramId {
            get {
                return this.StudyProgramIdField;
            }
            set {
                if ((this.StudyProgramIdField.Equals(value) != true)) {
                    this.StudyProgramIdField = value;
                    this.RaisePropertyChanged("StudyProgramId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Tuition {
            get {
                return this.TuitionField;
            }
            set {
                if ((this.TuitionField.Equals(value) != true)) {
                    this.TuitionField = value;
                    this.RaisePropertyChanged("Tuition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteFault", Namespace="http://schemas.datacontract.org/2004/07/WCFStudy")]
    [System.SerializableAttribute()]
    public partial class DeleteFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/Repository.Model")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FoundationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentHead {
            get {
                return this.DepartmentHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentHeadField, value) != true)) {
                    this.DepartmentHeadField = value;
                    this.RaisePropertyChanged("DepartmentHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FoundationYear {
            get {
                return this.FoundationYearField;
            }
            set {
                if ((this.FoundationYearField.Equals(value) != true)) {
                    this.FoundationYearField = value;
                    this.RaisePropertyChanged("FoundationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Professor", Namespace="http://schemas.datacontract.org/2004/07/Repository.Model")]
    [System.SerializableAttribute()]
    public partial class Professor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameAndSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProfessorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthPlace {
            get {
                return this.BirthPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthPlaceField, value) != true)) {
                    this.BirthPlaceField = value;
                    this.RaisePropertyChanged("BirthPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Education {
            get {
                return this.EducationField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationField, value) != true)) {
                    this.EducationField = value;
                    this.RaisePropertyChanged("Education");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameAndSurname {
            get {
                return this.NameAndSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameAndSurnameField, value) != true)) {
                    this.NameAndSurnameField = value;
                    this.RaisePropertyChanged("NameAndSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProfessorId {
            get {
                return this.ProfessorIdField;
            }
            set {
                if ((this.ProfessorIdField.Equals(value) != true)) {
                    this.ProfessorIdField = value;
                    this.RaisePropertyChanged("ProfessorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/Repository.Model")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssistantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ETCSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProfessorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfessorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudyProgramIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyProgramNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Assistant {
            get {
                return this.AssistantField;
            }
            set {
                if ((object.ReferenceEquals(this.AssistantField, value) != true)) {
                    this.AssistantField = value;
                    this.RaisePropertyChanged("Assistant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ETCS {
            get {
                return this.ETCSField;
            }
            set {
                if ((this.ETCSField.Equals(value) != true)) {
                    this.ETCSField = value;
                    this.RaisePropertyChanged("ETCS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProfessorId {
            get {
                return this.ProfessorIdField;
            }
            set {
                if ((this.ProfessorIdField.Equals(value) != true)) {
                    this.ProfessorIdField = value;
                    this.RaisePropertyChanged("ProfessorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfessorName {
            get {
                return this.ProfessorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessorNameField, value) != true)) {
                    this.ProfessorNameField = value;
                    this.RaisePropertyChanged("ProfessorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudyProgramId {
            get {
                return this.StudyProgramIdField;
            }
            set {
                if ((this.StudyProgramIdField.Equals(value) != true)) {
                    this.StudyProgramIdField = value;
                    this.RaisePropertyChanged("StudyProgramId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudyProgramName {
            get {
                return this.StudyProgramNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyProgramNameField, value) != true)) {
                    this.StudyProgramNameField = value;
                    this.RaisePropertyChanged("StudyProgramName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamPeriod", Namespace="http://schemas.datacontract.org/2004/07/Repository.Model")]
    [System.SerializableAttribute()]
    public partial class ExamPeriod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamPeriodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsApsolventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SchoolYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamPeriodId {
            get {
                return this.ExamPeriodIdField;
            }
            set {
                if ((this.ExamPeriodIdField.Equals(value) != true)) {
                    this.ExamPeriodIdField = value;
                    this.RaisePropertyChanged("ExamPeriodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsApsolvent {
            get {
                return this.IsApsolventField;
            }
            set {
                if ((this.IsApsolventField.Equals(value) != true)) {
                    this.IsApsolventField = value;
                    this.RaisePropertyChanged("IsApsolvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SchoolYear {
            get {
                return this.SchoolYearField;
            }
            set {
                if ((this.SchoolYearField.Equals(value) != true)) {
                    this.SchoolYearField = value;
                    this.RaisePropertyChanged("SchoolYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exam", Namespace="http://schemas.datacontract.org/2004/07/Repository.Model")]
    [System.SerializableAttribute()]
    public partial class Exam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamPeriodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamPeriodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsPassedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAndTime {
            get {
                return this.DateAndTimeField;
            }
            set {
                if ((this.DateAndTimeField.Equals(value) != true)) {
                    this.DateAndTimeField = value;
                    this.RaisePropertyChanged("DateAndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamId {
            get {
                return this.ExamIdField;
            }
            set {
                if ((this.ExamIdField.Equals(value) != true)) {
                    this.ExamIdField = value;
                    this.RaisePropertyChanged("ExamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamPeriodId {
            get {
                return this.ExamPeriodIdField;
            }
            set {
                if ((this.ExamPeriodIdField.Equals(value) != true)) {
                    this.ExamPeriodIdField = value;
                    this.RaisePropertyChanged("ExamPeriodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExamPeriodName {
            get {
                return this.ExamPeriodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamPeriodNameField, value) != true)) {
                    this.ExamPeriodNameField = value;
                    this.RaisePropertyChanged("ExamPeriodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsPassed {
            get {
                return this.IsPassedField;
            }
            set {
                if ((this.IsPassedField.Equals(value) != true)) {
                    this.IsPassedField = value;
                    this.RaisePropertyChanged("IsPassed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamRegistration", Namespace="http://schemas.datacontract.org/2004/07/Repository.Model")]
    [System.SerializableAttribute()]
    public partial class ExamRegistration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamRegistrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRegistredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNameAndSurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamId {
            get {
                return this.ExamIdField;
            }
            set {
                if ((this.ExamIdField.Equals(value) != true)) {
                    this.ExamIdField = value;
                    this.RaisePropertyChanged("ExamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamRegistrationId {
            get {
                return this.ExamRegistrationIdField;
            }
            set {
                if ((this.ExamRegistrationIdField.Equals(value) != true)) {
                    this.ExamRegistrationIdField = value;
                    this.RaisePropertyChanged("ExamRegistrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRegistred {
            get {
                return this.IsRegistredField;
            }
            set {
                if ((this.IsRegistredField.Equals(value) != true)) {
                    this.IsRegistredField = value;
                    this.RaisePropertyChanged("IsRegistred");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentNameAndSurname {
            get {
                return this.StudentNameAndSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNameAndSurnameField, value) != true)) {
                    this.StudentNameAndSurnameField = value;
                    this.RaisePropertyChanged("StudentNameAndSurname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamResult", Namespace="http://schemas.datacontract.org/2004/07/Repository.Model")]
    [System.SerializableAttribute()]
    public partial class ExamResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EvaluationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamRegistrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamResultsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FirstTestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecondTestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNameAndSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TermPaperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WritenExamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Evaluation {
            get {
                return this.EvaluationField;
            }
            set {
                if ((this.EvaluationField.Equals(value) != true)) {
                    this.EvaluationField = value;
                    this.RaisePropertyChanged("Evaluation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamRegistrationId {
            get {
                return this.ExamRegistrationIdField;
            }
            set {
                if ((this.ExamRegistrationIdField.Equals(value) != true)) {
                    this.ExamRegistrationIdField = value;
                    this.RaisePropertyChanged("ExamRegistrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamResultsId {
            get {
                return this.ExamResultsIdField;
            }
            set {
                if ((this.ExamResultsIdField.Equals(value) != true)) {
                    this.ExamResultsIdField = value;
                    this.RaisePropertyChanged("ExamResultsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstTest {
            get {
                return this.FirstTestField;
            }
            set {
                if ((this.FirstTestField.Equals(value) != true)) {
                    this.FirstTestField = value;
                    this.RaisePropertyChanged("FirstTest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondTest {
            get {
                return this.SecondTestField;
            }
            set {
                if ((this.SecondTestField.Equals(value) != true)) {
                    this.SecondTestField = value;
                    this.RaisePropertyChanged("SecondTest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentNameAndSurname {
            get {
                return this.StudentNameAndSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNameAndSurnameField, value) != true)) {
                    this.StudentNameAndSurnameField = value;
                    this.RaisePropertyChanged("StudentNameAndSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TermPaper {
            get {
                return this.TermPaperField;
            }
            set {
                if ((this.TermPaperField.Equals(value) != true)) {
                    this.TermPaperField = value;
                    this.RaisePropertyChanged("TermPaper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WritenExam {
            get {
                return this.WritenExamField;
            }
            set {
                if ((this.WritenExamField.Equals(value) != true)) {
                    this.WritenExamField = value;
                    this.RaisePropertyChanged("WritenExam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllStudents", ReplyAction="http://tempuri.org/IService/GetAllStudentsResponse")]
        System.Collections.Generic.List<WPFStudy.ServiceReference.Student> GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllStudents", ReplyAction="http://tempuri.org/IService/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Student>> GetAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddStudent", ReplyAction="http://tempuri.org/IService/AddStudentResponse")]
        WPFStudy.ServiceReference.Student AddStudent(WPFStudy.ServiceReference.Student newStudent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddStudent", ReplyAction="http://tempuri.org/IService/AddStudentResponse")]
        System.Threading.Tasks.Task<WPFStudy.ServiceReference.Student> AddStudentAsync(WPFStudy.ServiceReference.Student newStudent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditStudent", ReplyAction="http://tempuri.org/IService/EditStudentResponse")]
        void EditStudent(WPFStudy.ServiceReference.Student editedStudent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditStudent", ReplyAction="http://tempuri.org/IService/EditStudentResponse")]
        System.Threading.Tasks.Task EditStudentAsync(WPFStudy.ServiceReference.Student editedStudent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteStudent", ReplyAction="http://tempuri.org/IService/DeleteStudentResponse")]
        void DeleteStudent(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteStudent", ReplyAction="http://tempuri.org/IService/DeleteStudentResponse")]
        System.Threading.Tasks.Task DeleteStudentAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllStudyPrograms", ReplyAction="http://tempuri.org/IService/GetAllStudyProgramsResponse")]
        System.Collections.Generic.List<WPFStudy.ServiceReference.StudyProgram> GetAllStudyPrograms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllStudyPrograms", ReplyAction="http://tempuri.org/IService/GetAllStudyProgramsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.StudyProgram>> GetAllStudyProgramsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddStudyProgram", ReplyAction="http://tempuri.org/IService/AddStudyProgramResponse")]
        WPFStudy.ServiceReference.StudyProgram AddStudyProgram(WPFStudy.ServiceReference.StudyProgram newStudyProgram);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddStudyProgram", ReplyAction="http://tempuri.org/IService/AddStudyProgramResponse")]
        System.Threading.Tasks.Task<WPFStudy.ServiceReference.StudyProgram> AddStudyProgramAsync(WPFStudy.ServiceReference.StudyProgram newStudyProgram);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditStudyProgram", ReplyAction="http://tempuri.org/IService/EditStudyProgramResponse")]
        void EditStudyProgram(WPFStudy.ServiceReference.StudyProgram editedStudyProgram);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditStudyProgram", ReplyAction="http://tempuri.org/IService/EditStudyProgramResponse")]
        System.Threading.Tasks.Task EditStudyProgramAsync(WPFStudy.ServiceReference.StudyProgram editedStudyProgram);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteStudyProgram", ReplyAction="http://tempuri.org/IService/DeleteStudyProgramResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WPFStudy.ServiceReference.DeleteFault), Action="http://tempuri.org/IService/DeleteStudyProgramDeleteFaultFault", Name="DeleteFault", Namespace="http://schemas.datacontract.org/2004/07/WCFStudy")]
        void DeleteStudyProgram(int studyProgramId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteStudyProgram", ReplyAction="http://tempuri.org/IService/DeleteStudyProgramResponse")]
        System.Threading.Tasks.Task DeleteStudyProgramAsync(int studyProgramId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllDepartments", ReplyAction="http://tempuri.org/IService/GetAllDepartmentsResponse")]
        System.Collections.Generic.List<WPFStudy.ServiceReference.Department> GetAllDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllDepartments", ReplyAction="http://tempuri.org/IService/GetAllDepartmentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Department>> GetAllDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddDepartment", ReplyAction="http://tempuri.org/IService/AddDepartmentResponse")]
        WPFStudy.ServiceReference.Department AddDepartment(WPFStudy.ServiceReference.Department newDepartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddDepartment", ReplyAction="http://tempuri.org/IService/AddDepartmentResponse")]
        System.Threading.Tasks.Task<WPFStudy.ServiceReference.Department> AddDepartmentAsync(WPFStudy.ServiceReference.Department newDepartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditDepartment", ReplyAction="http://tempuri.org/IService/EditDepartmentResponse")]
        void EditDepartment(WPFStudy.ServiceReference.Department editedDepartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditDepartment", ReplyAction="http://tempuri.org/IService/EditDepartmentResponse")]
        System.Threading.Tasks.Task EditDepartmentAsync(WPFStudy.ServiceReference.Department editedDepartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDepartment", ReplyAction="http://tempuri.org/IService/DeleteDepartmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WPFStudy.ServiceReference.DeleteFault), Action="http://tempuri.org/IService/DeleteDepartmentDeleteFaultFault", Name="DeleteFault", Namespace="http://schemas.datacontract.org/2004/07/WCFStudy")]
        void DeleteDepartment(int departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDepartment", ReplyAction="http://tempuri.org/IService/DeleteDepartmentResponse")]
        System.Threading.Tasks.Task DeleteDepartmentAsync(int departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllSPForDepartmentId", ReplyAction="http://tempuri.org/IService/GetAllSPForDepartmentIdResponse")]
        System.Collections.Generic.List<WPFStudy.ServiceReference.StudyProgram> GetAllSPForDepartmentId(int departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllSPForDepartmentId", ReplyAction="http://tempuri.org/IService/GetAllSPForDepartmentIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.StudyProgram>> GetAllSPForDepartmentIdAsync(int departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllProfessors", ReplyAction="http://tempuri.org/IService/GetAllProfessorsResponse")]
        System.Collections.Generic.List<WPFStudy.ServiceReference.Professor> GetAllProfessors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllProfessors", ReplyAction="http://tempuri.org/IService/GetAllProfessorsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Professor>> GetAllProfessorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddProfessor", ReplyAction="http://tempuri.org/IService/AddProfessorResponse")]
        WPFStudy.ServiceReference.Professor AddProfessor(WPFStudy.ServiceReference.Professor newProfessor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddProfessor", ReplyAction="http://tempuri.org/IService/AddProfessorResponse")]
        System.Threading.Tasks.Task<WPFStudy.ServiceReference.Professor> AddProfessorAsync(WPFStudy.ServiceReference.Professor newProfessor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditProfessor", ReplyAction="http://tempuri.org/IService/EditProfessorResponse")]
        void EditProfessor(WPFStudy.ServiceReference.Professor editedProfessor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditProfessor", ReplyAction="http://tempuri.org/IService/EditProfessorResponse")]
        System.Threading.Tasks.Task EditProfessorAsync(WPFStudy.ServiceReference.Professor editedProfessor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteProfessor", ReplyAction="http://tempuri.org/IService/DeleteProfessorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WPFStudy.ServiceReference.DeleteFault), Action="http://tempuri.org/IService/DeleteProfessorDeleteFaultFault", Name="DeleteFault", Namespace="http://schemas.datacontract.org/2004/07/WCFStudy")]
        void DeleteProfessor(int professorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteProfessor", ReplyAction="http://tempuri.org/IService/DeleteProfessorResponse")]
        System.Threading.Tasks.Task DeleteProfessorAsync(int professorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllCourses", ReplyAction="http://tempuri.org/IService/GetAllCoursesResponse")]
        System.Collections.Generic.List<WPFStudy.ServiceReference.Course> GetAllCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllCourses", ReplyAction="http://tempuri.org/IService/GetAllCoursesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Course>> GetAllCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddCourse", ReplyAction="http://tempuri.org/IService/AddCourseResponse")]
        WPFStudy.ServiceReference.Course AddCourse(WPFStudy.ServiceReference.Course newCourse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddCourse", ReplyAction="http://tempuri.org/IService/AddCourseResponse")]
        System.Threading.Tasks.Task<WPFStudy.ServiceReference.Course> AddCourseAsync(WPFStudy.ServiceReference.Course newCourse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditCourse", ReplyAction="http://tempuri.org/IService/EditCourseResponse")]
        void EditCourse(WPFStudy.ServiceReference.Course editedCourse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditCourse", ReplyAction="http://tempuri.org/IService/EditCourseResponse")]
        System.Threading.Tasks.Task EditCourseAsync(WPFStudy.ServiceReference.Course editedCourse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteCourse", ReplyAction="http://tempuri.org/IService/DeleteCourseResponse")]
        void DeleteCourse(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteCourse", ReplyAction="http://tempuri.org/IService/DeleteCourseResponse")]
        System.Threading.Tasks.Task DeleteCourseAsync(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllExamPeriods", ReplyAction="http://tempuri.org/IService/GetAllExamPeriodsResponse")]
        System.Collections.Generic.List<WPFStudy.ServiceReference.ExamPeriod> GetAllExamPeriods();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllExamPeriods", ReplyAction="http://tempuri.org/IService/GetAllExamPeriodsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.ExamPeriod>> GetAllExamPeriodsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddExamPeriod", ReplyAction="http://tempuri.org/IService/AddExamPeriodResponse")]
        WPFStudy.ServiceReference.ExamPeriod AddExamPeriod(WPFStudy.ServiceReference.ExamPeriod newExamPeriod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddExamPeriod", ReplyAction="http://tempuri.org/IService/AddExamPeriodResponse")]
        System.Threading.Tasks.Task<WPFStudy.ServiceReference.ExamPeriod> AddExamPeriodAsync(WPFStudy.ServiceReference.ExamPeriod newExamPeriod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditExamPeriod", ReplyAction="http://tempuri.org/IService/EditExamPeriodResponse")]
        void EditExamPeriod(WPFStudy.ServiceReference.ExamPeriod editedExamPeriod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditExamPeriod", ReplyAction="http://tempuri.org/IService/EditExamPeriodResponse")]
        System.Threading.Tasks.Task EditExamPeriodAsync(WPFStudy.ServiceReference.ExamPeriod editedExamPeriod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteExamPeriod", ReplyAction="http://tempuri.org/IService/DeleteExamPeriodResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WPFStudy.ServiceReference.DeleteFault), Action="http://tempuri.org/IService/DeleteExamPeriodDeleteFaultFault", Name="DeleteFault", Namespace="http://schemas.datacontract.org/2004/07/WCFStudy")]
        void DeleteExamPeriod(int examPeriodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteExamPeriod", ReplyAction="http://tempuri.org/IService/DeleteExamPeriodResponse")]
        System.Threading.Tasks.Task DeleteExamPeriodAsync(int examPeriodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllExams", ReplyAction="http://tempuri.org/IService/GetAllExamsResponse")]
        System.Collections.Generic.List<WPFStudy.ServiceReference.Exam> GetAllExams();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllExams", ReplyAction="http://tempuri.org/IService/GetAllExamsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Exam>> GetAllExamsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddExam", ReplyAction="http://tempuri.org/IService/AddExamResponse")]
        WPFStudy.ServiceReference.Exam AddExam(WPFStudy.ServiceReference.Exam newExam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddExam", ReplyAction="http://tempuri.org/IService/AddExamResponse")]
        System.Threading.Tasks.Task<WPFStudy.ServiceReference.Exam> AddExamAsync(WPFStudy.ServiceReference.Exam newExam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditExam", ReplyAction="http://tempuri.org/IService/EditExamResponse")]
        void EditExam(WPFStudy.ServiceReference.Exam editedExam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditExam", ReplyAction="http://tempuri.org/IService/EditExamResponse")]
        System.Threading.Tasks.Task EditExamAsync(WPFStudy.ServiceReference.Exam editedExam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteExam", ReplyAction="http://tempuri.org/IService/DeleteExamResponse")]
        void DeleteExam(int examId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteExam", ReplyAction="http://tempuri.org/IService/DeleteExamResponse")]
        System.Threading.Tasks.Task DeleteExamAsync(int examId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetActiveExamPeriods", ReplyAction="http://tempuri.org/IService/GetActiveExamPeriodsResponse")]
        System.Collections.Generic.List<WPFStudy.ServiceReference.ExamPeriod> GetActiveExamPeriods();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetActiveExamPeriods", ReplyAction="http://tempuri.org/IService/GetActiveExamPeriodsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.ExamPeriod>> GetActiveExamPeriodsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProfessorCourses", ReplyAction="http://tempuri.org/IService/GetProfessorCoursesResponse")]
        System.Collections.Generic.List<WPFStudy.ServiceReference.Course> GetProfessorCourses(int professorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProfessorCourses", ReplyAction="http://tempuri.org/IService/GetProfessorCoursesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Course>> GetProfessorCoursesAsync(int professorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRegistredStudentsForExam", ReplyAction="http://tempuri.org/IService/GetRegistredStudentsForExamResponse")]
        System.Collections.Generic.Dictionary<System.Collections.Generic.List<WPFStudy.ServiceReference.ExamRegistration>, System.Collections.Generic.List<object>> GetRegistredStudentsForExam(int courseId, int examPeriodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRegistredStudentsForExam", ReplyAction="http://tempuri.org/IService/GetRegistredStudentsForExamResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<System.Collections.Generic.List<WPFStudy.ServiceReference.ExamRegistration>, System.Collections.Generic.List<object>>> GetRegistredStudentsForExamAsync(int courseId, int examPeriodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetExamResults", ReplyAction="http://tempuri.org/IService/SetExamResultsResponse")]
        bool SetExamResults(System.Collections.Generic.List<WPFStudy.ServiceReference.ExamResult> examResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetExamResults", ReplyAction="http://tempuri.org/IService/SetExamResultsResponse")]
        System.Threading.Tasks.Task<bool> SetExamResultsAsync(System.Collections.Generic.List<WPFStudy.ServiceReference.ExamResult> examResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidateExamPeriodActivity", ReplyAction="http://tempuri.org/IService/ValidateExamPeriodActivityResponse")]
        bool ValidateExamPeriodActivity(System.DateTime startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidateExamPeriodActivity", ReplyAction="http://tempuri.org/IService/ValidateExamPeriodActivityResponse")]
        System.Threading.Tasks.Task<bool> ValidateExamPeriodActivityAsync(System.DateTime startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidateExamInExamPeriod", ReplyAction="http://tempuri.org/IService/ValidateExamInExamPeriodResponse")]
        bool ValidateExamInExamPeriod(int examPeriodId, int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidateExamInExamPeriod", ReplyAction="http://tempuri.org/IService/ValidateExamInExamPeriodResponse")]
        System.Threading.Tasks.Task<bool> ValidateExamInExamPeriodAsync(int examPeriodId, int courseId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WPFStudy.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WPFStudy.ServiceReference.IService>, WPFStudy.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WPFStudy.ServiceReference.Student> GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Student>> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
        
        public WPFStudy.ServiceReference.Student AddStudent(WPFStudy.ServiceReference.Student newStudent) {
            return base.Channel.AddStudent(newStudent);
        }
        
        public System.Threading.Tasks.Task<WPFStudy.ServiceReference.Student> AddStudentAsync(WPFStudy.ServiceReference.Student newStudent) {
            return base.Channel.AddStudentAsync(newStudent);
        }
        
        public void EditStudent(WPFStudy.ServiceReference.Student editedStudent) {
            base.Channel.EditStudent(editedStudent);
        }
        
        public System.Threading.Tasks.Task EditStudentAsync(WPFStudy.ServiceReference.Student editedStudent) {
            return base.Channel.EditStudentAsync(editedStudent);
        }
        
        public void DeleteStudent(int studentId) {
            base.Channel.DeleteStudent(studentId);
        }
        
        public System.Threading.Tasks.Task DeleteStudentAsync(int studentId) {
            return base.Channel.DeleteStudentAsync(studentId);
        }
        
        public System.Collections.Generic.List<WPFStudy.ServiceReference.StudyProgram> GetAllStudyPrograms() {
            return base.Channel.GetAllStudyPrograms();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.StudyProgram>> GetAllStudyProgramsAsync() {
            return base.Channel.GetAllStudyProgramsAsync();
        }
        
        public WPFStudy.ServiceReference.StudyProgram AddStudyProgram(WPFStudy.ServiceReference.StudyProgram newStudyProgram) {
            return base.Channel.AddStudyProgram(newStudyProgram);
        }
        
        public System.Threading.Tasks.Task<WPFStudy.ServiceReference.StudyProgram> AddStudyProgramAsync(WPFStudy.ServiceReference.StudyProgram newStudyProgram) {
            return base.Channel.AddStudyProgramAsync(newStudyProgram);
        }
        
        public void EditStudyProgram(WPFStudy.ServiceReference.StudyProgram editedStudyProgram) {
            base.Channel.EditStudyProgram(editedStudyProgram);
        }
        
        public System.Threading.Tasks.Task EditStudyProgramAsync(WPFStudy.ServiceReference.StudyProgram editedStudyProgram) {
            return base.Channel.EditStudyProgramAsync(editedStudyProgram);
        }
        
        public void DeleteStudyProgram(int studyProgramId) {
            base.Channel.DeleteStudyProgram(studyProgramId);
        }
        
        public System.Threading.Tasks.Task DeleteStudyProgramAsync(int studyProgramId) {
            return base.Channel.DeleteStudyProgramAsync(studyProgramId);
        }
        
        public System.Collections.Generic.List<WPFStudy.ServiceReference.Department> GetAllDepartments() {
            return base.Channel.GetAllDepartments();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Department>> GetAllDepartmentsAsync() {
            return base.Channel.GetAllDepartmentsAsync();
        }
        
        public WPFStudy.ServiceReference.Department AddDepartment(WPFStudy.ServiceReference.Department newDepartment) {
            return base.Channel.AddDepartment(newDepartment);
        }
        
        public System.Threading.Tasks.Task<WPFStudy.ServiceReference.Department> AddDepartmentAsync(WPFStudy.ServiceReference.Department newDepartment) {
            return base.Channel.AddDepartmentAsync(newDepartment);
        }
        
        public void EditDepartment(WPFStudy.ServiceReference.Department editedDepartment) {
            base.Channel.EditDepartment(editedDepartment);
        }
        
        public System.Threading.Tasks.Task EditDepartmentAsync(WPFStudy.ServiceReference.Department editedDepartment) {
            return base.Channel.EditDepartmentAsync(editedDepartment);
        }
        
        public void DeleteDepartment(int departmentId) {
            base.Channel.DeleteDepartment(departmentId);
        }
        
        public System.Threading.Tasks.Task DeleteDepartmentAsync(int departmentId) {
            return base.Channel.DeleteDepartmentAsync(departmentId);
        }
        
        public System.Collections.Generic.List<WPFStudy.ServiceReference.StudyProgram> GetAllSPForDepartmentId(int departmentId) {
            return base.Channel.GetAllSPForDepartmentId(departmentId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.StudyProgram>> GetAllSPForDepartmentIdAsync(int departmentId) {
            return base.Channel.GetAllSPForDepartmentIdAsync(departmentId);
        }
        
        public System.Collections.Generic.List<WPFStudy.ServiceReference.Professor> GetAllProfessors() {
            return base.Channel.GetAllProfessors();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Professor>> GetAllProfessorsAsync() {
            return base.Channel.GetAllProfessorsAsync();
        }
        
        public WPFStudy.ServiceReference.Professor AddProfessor(WPFStudy.ServiceReference.Professor newProfessor) {
            return base.Channel.AddProfessor(newProfessor);
        }
        
        public System.Threading.Tasks.Task<WPFStudy.ServiceReference.Professor> AddProfessorAsync(WPFStudy.ServiceReference.Professor newProfessor) {
            return base.Channel.AddProfessorAsync(newProfessor);
        }
        
        public void EditProfessor(WPFStudy.ServiceReference.Professor editedProfessor) {
            base.Channel.EditProfessor(editedProfessor);
        }
        
        public System.Threading.Tasks.Task EditProfessorAsync(WPFStudy.ServiceReference.Professor editedProfessor) {
            return base.Channel.EditProfessorAsync(editedProfessor);
        }
        
        public void DeleteProfessor(int professorId) {
            base.Channel.DeleteProfessor(professorId);
        }
        
        public System.Threading.Tasks.Task DeleteProfessorAsync(int professorId) {
            return base.Channel.DeleteProfessorAsync(professorId);
        }
        
        public System.Collections.Generic.List<WPFStudy.ServiceReference.Course> GetAllCourses() {
            return base.Channel.GetAllCourses();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Course>> GetAllCoursesAsync() {
            return base.Channel.GetAllCoursesAsync();
        }
        
        public WPFStudy.ServiceReference.Course AddCourse(WPFStudy.ServiceReference.Course newCourse) {
            return base.Channel.AddCourse(newCourse);
        }
        
        public System.Threading.Tasks.Task<WPFStudy.ServiceReference.Course> AddCourseAsync(WPFStudy.ServiceReference.Course newCourse) {
            return base.Channel.AddCourseAsync(newCourse);
        }
        
        public void EditCourse(WPFStudy.ServiceReference.Course editedCourse) {
            base.Channel.EditCourse(editedCourse);
        }
        
        public System.Threading.Tasks.Task EditCourseAsync(WPFStudy.ServiceReference.Course editedCourse) {
            return base.Channel.EditCourseAsync(editedCourse);
        }
        
        public void DeleteCourse(int courseId) {
            base.Channel.DeleteCourse(courseId);
        }
        
        public System.Threading.Tasks.Task DeleteCourseAsync(int courseId) {
            return base.Channel.DeleteCourseAsync(courseId);
        }
        
        public System.Collections.Generic.List<WPFStudy.ServiceReference.ExamPeriod> GetAllExamPeriods() {
            return base.Channel.GetAllExamPeriods();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.ExamPeriod>> GetAllExamPeriodsAsync() {
            return base.Channel.GetAllExamPeriodsAsync();
        }
        
        public WPFStudy.ServiceReference.ExamPeriod AddExamPeriod(WPFStudy.ServiceReference.ExamPeriod newExamPeriod) {
            return base.Channel.AddExamPeriod(newExamPeriod);
        }
        
        public System.Threading.Tasks.Task<WPFStudy.ServiceReference.ExamPeriod> AddExamPeriodAsync(WPFStudy.ServiceReference.ExamPeriod newExamPeriod) {
            return base.Channel.AddExamPeriodAsync(newExamPeriod);
        }
        
        public void EditExamPeriod(WPFStudy.ServiceReference.ExamPeriod editedExamPeriod) {
            base.Channel.EditExamPeriod(editedExamPeriod);
        }
        
        public System.Threading.Tasks.Task EditExamPeriodAsync(WPFStudy.ServiceReference.ExamPeriod editedExamPeriod) {
            return base.Channel.EditExamPeriodAsync(editedExamPeriod);
        }
        
        public void DeleteExamPeriod(int examPeriodId) {
            base.Channel.DeleteExamPeriod(examPeriodId);
        }
        
        public System.Threading.Tasks.Task DeleteExamPeriodAsync(int examPeriodId) {
            return base.Channel.DeleteExamPeriodAsync(examPeriodId);
        }
        
        public System.Collections.Generic.List<WPFStudy.ServiceReference.Exam> GetAllExams() {
            return base.Channel.GetAllExams();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Exam>> GetAllExamsAsync() {
            return base.Channel.GetAllExamsAsync();
        }
        
        public WPFStudy.ServiceReference.Exam AddExam(WPFStudy.ServiceReference.Exam newExam) {
            return base.Channel.AddExam(newExam);
        }
        
        public System.Threading.Tasks.Task<WPFStudy.ServiceReference.Exam> AddExamAsync(WPFStudy.ServiceReference.Exam newExam) {
            return base.Channel.AddExamAsync(newExam);
        }
        
        public void EditExam(WPFStudy.ServiceReference.Exam editedExam) {
            base.Channel.EditExam(editedExam);
        }
        
        public System.Threading.Tasks.Task EditExamAsync(WPFStudy.ServiceReference.Exam editedExam) {
            return base.Channel.EditExamAsync(editedExam);
        }
        
        public void DeleteExam(int examId) {
            base.Channel.DeleteExam(examId);
        }
        
        public System.Threading.Tasks.Task DeleteExamAsync(int examId) {
            return base.Channel.DeleteExamAsync(examId);
        }
        
        public System.Collections.Generic.List<WPFStudy.ServiceReference.ExamPeriod> GetActiveExamPeriods() {
            return base.Channel.GetActiveExamPeriods();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.ExamPeriod>> GetActiveExamPeriodsAsync() {
            return base.Channel.GetActiveExamPeriodsAsync();
        }
        
        public System.Collections.Generic.List<WPFStudy.ServiceReference.Course> GetProfessorCourses(int professorId) {
            return base.Channel.GetProfessorCourses(professorId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WPFStudy.ServiceReference.Course>> GetProfessorCoursesAsync(int professorId) {
            return base.Channel.GetProfessorCoursesAsync(professorId);
        }
        
        public System.Collections.Generic.Dictionary<System.Collections.Generic.List<WPFStudy.ServiceReference.ExamRegistration>, System.Collections.Generic.List<object>> GetRegistredStudentsForExam(int courseId, int examPeriodId) {
            return base.Channel.GetRegistredStudentsForExam(courseId, examPeriodId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<System.Collections.Generic.List<WPFStudy.ServiceReference.ExamRegistration>, System.Collections.Generic.List<object>>> GetRegistredStudentsForExamAsync(int courseId, int examPeriodId) {
            return base.Channel.GetRegistredStudentsForExamAsync(courseId, examPeriodId);
        }
        
        public bool SetExamResults(System.Collections.Generic.List<WPFStudy.ServiceReference.ExamResult> examResults) {
            return base.Channel.SetExamResults(examResults);
        }
        
        public System.Threading.Tasks.Task<bool> SetExamResultsAsync(System.Collections.Generic.List<WPFStudy.ServiceReference.ExamResult> examResults) {
            return base.Channel.SetExamResultsAsync(examResults);
        }
        
        public bool ValidateExamPeriodActivity(System.DateTime startDate) {
            return base.Channel.ValidateExamPeriodActivity(startDate);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateExamPeriodActivityAsync(System.DateTime startDate) {
            return base.Channel.ValidateExamPeriodActivityAsync(startDate);
        }
        
        public bool ValidateExamInExamPeriod(int examPeriodId, int courseId) {
            return base.Channel.ValidateExamInExamPeriod(examPeriodId, courseId);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateExamInExamPeriodAsync(int examPeriodId, int courseId) {
            return base.Channel.ValidateExamInExamPeriodAsync(examPeriodId, courseId);
        }
    }
}
